### ISSUE TITLE
Validate certs do not work with the last release

### ISSUE THREAD

**Issue by N00B-Man** [Dynatrace/Dynatrace-OneAgent-Ansible#28]
I was trying to install the oneagent with the parameter validate_certs=false. I installed the role from ansible galaxy however it did not work. Upon troubleshooting found that the Variable was not present in the role. 
There is a commit on this Repo which has fixed it 13 months ago but it is not updated in Ansible Galaxy. Please create a new release in Ansible Galaxy.

**Comment by luisr-escobar** [comment]
Created [release 1.0.8](https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible/releases/tag/v1.0.8)
