### ISSUE TITLE
Document that Ansible >= 2.3.0 is required

### ISSUE THREAD

**Issue by centic9** [Dynatrace/Dynatrace-OneAgent-Ansible#3]
The "name" for blocks in main.yml require Ansible 2.3.0 or higher, see https://github.com/ansible/ansible/issues/18985 and https://github.com/ansible/ansible/commit/fcb033b9e442e7e49921817729169a14ba53d99d, would be good to document that requirement as e.g. Ubuntu LTS (Xenial) still has 2.1.1.

**Comment by centic9** [comment]
Alternatively removing the "name" from main.yml makes it run on older versions of Ansible.

**Comment by BlazejT** [comment]
Thanks, we approved changes and merged them to master.
