### ISSUE TITLE
Installation of OneAgent is not idempotent

### ISSUE THREAD

**Issue by centic9** [Dynatrace/Dynatrace-OneAgent-Ansible#4]
The playbook downloads and installs the agent even if it already exists. 

In general playbooks should be idempotent and not repeat actions that have already been done before.

**Comment by BlazejT** [comment]
Thanks, we approved changes and merged them to master.

If any question arises - OneAgent is being update automatically based on the specified OneAgent version in the tenant configuration on the cluster.
