### ISSUE TITLE
INFRA_ONLY and  APP_LOG_CONTENT_ACCESS are not included in the installer script.

### ISSUE THREAD

**Issue by dannywillford** [Dynatrace/Dynatrace-OneAgent-Ansible#6]
We have several applications in our environment.  Some of those servers require us to have INFRA_ONLY enabled and APP_LOG_CONTENT_ACCESS disabled.  As we are using ansible for deploying we require the ability to change these variables as needed.

**Comment by dannywillford** [comment]
#7 A pull request has been submitted for this issue.

**Comment by MarcinZejer** [comment]
Thanks for help!
Fixed by #10
