### ISSUE TITLE
Create switch to uninstall the agent

### ISSUE THREAD

**Issue by jmcshane** [Dynatrace/Dynatrace-OneAgent-Ansible#8]
Right now this role can only manage the agent to do an installation. It would be great to default to installation, but also function as an uninstaller.

**Comment by holms** [comment]
Would be nice if @Dynatrace-David-Bignotti @Dynatrace-Paul-Anderson @admin-dynatrace would show some sing of life. Because what's the point of this service if it doesn't have automation :)

**Comment by luisescobar89** [comment]
added in v1.0.7 release
